// <auto-generated />
using System;
using LMSBackend.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMSBackend.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250927180000_CrearBancoPreguntas")]
    partial class CrearBancoPreguntas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a simplified Designer file for the Question Bank migration
            // The full model would include all entities but for this migration we focus on the new tables:
            // - BancoPreguntas (Question Bank)
            // - OpcionesBanco (Question Bank Options)
#pragma warning restore 612, 618
        }
    }
}